version: "3.9"
services:
  api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/
      - DB_HOST=postgres
      - DB_NAME=tourisme_dw
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_PORT=5432
    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_started
  ingestor:
    build: .
    container_name: etl_pipeline
    command: ["python", "main.py"]
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: tourisme_dw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  mongo-express:
    image: mongo-express
    container_name: mongo_ui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      mongodb:
        condition: service_healthy
    restart: on-failure
volumes:
  mongo_data:
  postgres_data: